[package]
name = "lean-rewrite-search"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "c2bb4c5cf85ba25891cd58f96f6073c4d4df758e"}
libk = {git = "https://github.com/khoek/libk", rev = "461caf0b2915dd612a5e9f4ad7f6b627506d4ec0"}
libiconfig = {git = "https://github.com/khoek/libiconfig", rev = "8f7c9d988fdedef81114c34b96e938d3f6231815"}
